### ISSUE TITLE
feature voting is down!

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#100]
![image](https://user-images.githubusercontent.com/1839645/90301902-72eee000-de57-11ea-8420-1b1444bd32dc.png)

**Comment by chrisjsewell** [comment]
This may be due to the "hack" I mentioned in https://github.com/jupyterhub/team-compass/issues/326#issuecomment-667287037; that I am obtaining https://github.com/executablebooks/meta/releases/download/issues/issues.json *via* the cors-anywhere proxy server, because otherwise it wont download due to a CORS authentication issue.
So I don't know if the 429 is coming from too many requests to cors-anywhere, or cors-anywhere sending  too many requests to github. Either way it would be ideal if there was a better place to upload the issues.json to?

**Comment by choldgraf** [comment]
Could we embed it in the repository itself?

**Comment by chrisjsewell** [comment]
If you're happy for there to be a commit every hour to this repo (and RTD rebuild) 😕

**Comment by choldgraf** [comment]
Maybe we change it to once a day? I dunno that wouldn't be so bad...but I agree sub-optimal

**Comment by chrisjsewell** [comment]
FYI its working fine for me

**Comment by chrisjsewell** [comment]
> Maybe we change it to once a day? I dunno that wouldn't be so bad...but I agree sub-optimal

Particularly if we wanted to do #92, this isn't really a viable option

**Comment by choldgraf** [comment]
Cool, maybe just unreliable then but I don't think it's a big deal

**Comment by chrisjsewell** [comment]
yeh I'll definitely try and think of a better solution though

**Comment by choldgraf** [comment]
👍 I'll close this one then
