### ISSUE TITLE
Apply for an EOSS grant

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#287]
# Background

CZI has [another round of their Essential Open Source Support](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/) grant series open. Letters of intent are due March 30th (full proposals due several weeks later).

I think there is much work that could be done in the Jupyter Book / Executable Books ecosystem, much more than we could carry on our Sloan grant alone. A few ideas for things that we could pitch:

- Development that was focused around enriching the "publishing" side of Jupyter Book (e.g., adding directives or features for common publishing things like appendices etc, or adding native support for "authors and titles")
- Development that focused around bridging Jupyter Book and Jupyter Lab / other interfaces (e.g., MyST support in those interfaces etc)
- Connections with the ReadTheDocs community to get JB support and documentation on there (either dev in Jupyter Book, or dev in RTD, or both)
- Connections with the broader docs/Sphinx dev community to improve shared infrastructure (e.g., #279)
- Connections with other communities that heavily use Jupyter Book (e.g., I believe that @sgibson91 mentioned that the Turing Way community may be interested in partnering with Jupyter Book on some ideas?)

# Questions

- Shall we apply for an EOSS grant?
- If so, any particular idea jump out at you as interesting to pursue? (either from the list above, or other ideas)
- Is anyone interested in helping wrangle and write a bit? (the application process isn't super hard, but will take some coordination and writing!)

cc @pradyunsg and @sgibson91 and @cooperrc who I'm not sure get pinged by this repo but may be interested, and the @executablebooks/ebpteam who I imagine will be interested in this! :-)

**Comment by chrisjsewell** [comment]
> Development that focused around bridging Jupyter Book and Jupyter Lab / other interfaces (e.g., MyST support in those interfaces etc)

Definitely interested in this, and also tying it in with my work on https://github.com/executablebooks/myst-language-support and https://github.com/chrisjsewell/rst-language-server
I guess maybe I could be coerced into a bit of writing 😆

**Comment by cooperrc** [comment]
> If so, any particular idea jump out at you as interesting to pursue? (either from the list above, or other ideas)

A big focus for CZI is on the role of FOSS in biomedical applications. Jupyter Book could play a huge role in this field, but its not widely established _yet_. I think exploring the publishing/bridging side of Jupyter Book might have a strong proposal: 
- Jupyter(Lab) is an essential resource for medicine and bioinformatics
- Jupyter Book creates reproducible research used in education
- we propose extending the Jupyter(Lab) interface with Jupyter Book features 
- users will have interactive medicine and bioinformatics computing environment that can be published in transparent and reproducible way

> Is anyone interested in helping wrangle and write a bit? (the application process isn't super hard, but will take some coordination and writing!)

count me in, let me know how I can help :+1:

**Comment by KirstieJane** [comment]
Heya! I would LOVE for JupyterBook to put in an EOSS grant. And _The Turing Way_ would be extremely keen to support the application. Whatever you choose I'm sure we'll be happy with but let me ping out my personal dream and see if it can be integrated into any of the other plans!

* Book: https://the-turing-way.netlify.app/welcome
* GitHub: https://github.com/alan-turing-institute/the-turing-way

## Existing resources / early plans

Firstly, let me make sure that you know about two potential connections that are created / ongoing but need sustaining / maintaining / promoting.

* We'd love for the tutorial that @malvikasharan, @martinagvilas and @sgibson91 made for JupyterCon2020 to be shared more widely (updated as needed etc) https://github.com/jupytercon/2020-jupyterbook-with-turing-way.
* We have a Google Summer of Code student project open to look at persona based exploration of how to navigate the book  https://github.com/alan-turing-institute/the-turing-way/blob/master/communications/GSoC-applications/GSoC-2021/GSoC-2021-INCF.md. We might not find someone suitable (we've set a decently high bar - but please do get in touch if anyone knows someone who would be interested!! https://github.com/alan-turing-institute/the-turing-way/issues/1787)

## Kirstie's dream :rocket: 🌟 

We find that _The Turing Way_ book is super intimidating for folks. There are loads of chapters, lots of content and I often hear "I'll read the book and get back to you" and .... well..... they don't. Because there's too much there to digest!

BUT - what if we could host subsections of the Jupyter Book in a "choose your own adventure" or "curate the reading list" format?

Then we could have views that said "Are you new to reproducibility? Would you like to learn about data management? How much time do you have (5 mins, 15 mins, 1 hour)?" and then someone could click through to answer those questions and see BOOM - their personally curated book!

All the content would be the same but we'd serve just a subsection of the content. I think it makes the book more accessible AND it really showcases the power of WHY you'd want to host a book online rather than just print out a PDF etc.

There's another small point which could fit in which is to customise the views - for example making a cover page - would be useful! We've found that seeing _all_ the possibilities right at the start is what makes people anxious 🤗

**Comment by choldgraf** [comment]
Thanks everybody for this super helpful set of ideas! I will digest a bit and think! In the meantime I also wanted to share a conversation around publishing pipelines with Jupyter that many may also be interested in...not sure if/how it relates to this, but maybe it sparks some ideas?

https://discourse.jupyter.org/t/feature-idea-jupyterhub-binderhub-jupyter-book-as-a-publishing-platform/8359/8

**Comment by ericholscher** [comment]
> Connections with the ReadTheDocs community to get JB support and documentation on there (either dev in Jupyter Book, or dev in RTD, or both)

We're a strong 👍  on this. We'd love to support this work, but we definitely would need more resources in a sustained manner to do this work. Having it be a CZI grant-funded role to at least handle part-time support, implementation, and maintenance of the integration between Jupyterbook & RTD would definitely allow us to support Jupyterbook.

I think there's already been a decent bit of research into what is required here in https://github.com/executablebooks/jupyter-book/issues/1091 and from folks on our team. We'd be :+1: to support an EBP grant on this work, or that included this work. 

Let me know what we can do to more this forward, since I know the application deadline is coming up soon.

**Comment by choldgraf** [comment]
OK I thought a bit and whipped together this Letter of Intent for a proposal around the theme of **Improving scientific publishing in the Jupyter ecosystem**. Here's a rough draft:

https://docs.google.com/document/d/1mHqUmGeu1Y6YTCZLxa7EZSLExlRXtUUJQXncN97Kb6U/edit?usp=sharing

Rather than focusing on just the authoring pieces, it focuses on doing focused development + integration across many tools in the Jupyter ecosystem in order to create an "end to end" publishing workflow that could be replicated for many communities.

After writing it down I am not 100% sold on it, nor am I sure that it is quite the right grant for this EOSS series - so happy to chat about other ideas or venues if people have them.

Would love to hear people's thoughts - I also have a few specific questions:

1. Is this the right scope for a proposal? It is very broad, but I think would have high impact.
2. Is this grant series the right target for this proposal? Or do you think it is ambitious enough to warrant a different target for funding?
3. Is the breakdown of roles correct? It is roughly 25% hub/cloud, 50% jupyter book / myst, and 50% JupyterLab
4. What would be the organization that accepts this money? Should it be a collection of organizations? (I think that 2i2c could hire several of the folks on there, but perhaps others are interested in participating as well?)

**Comment by choldgraf** [comment]
Hey all - I haven't gotten a ton of feedback on this, which makes me wonder if

1. I haven't gotten the scope of the proposal correct
2. That folks are stretched too thin to work on this

Unless I hear a clear positive signal from others, I will plan to *not* submit an EOSS proposal for the ExecutableBooks project, and instead focus efforts on smaller more focused proposals as the opportunity arises.

**Comment by cooperrc** [comment]
> Hey all - I haven't gotten a ton of feedback on this, which makes me wonder if
> 
> 1. I haven't gotten the scope of the proposal correct
> 2. That folks are stretched too thin to work on this
> 
> Unless I hear a clear positive signal from others, I will plan to _not_ submit an EOSS proposal for the ExecutableBooks project, and instead focus efforts on smaller more focused proposals as the opportunity arises. I am also trying to coordinate two EOSS proposals on the JupyterHub/Binder side of things, and this is stretching me quite thin, so I don't know that I have the cycles to re-work this one with a better focus etc

@choldgraf, I added some comments to shift focus to some combination of "transparency", "open science", and "reproducibility". I think we can get the work done, but the immediate benefit to biomed users would be kind of an "easy-share" button. They could generate reports, blogs, training docs, etc. The end-to-end publishing would be an awesome future application, but the problems in the proposal will have to be ironed out before there's a new "Jupyter Journal".

**Comment by choldgraf** [comment]
I think that is a great idea to improve the scope of narrative. Thanks for that!

I think where I’m a little bit more uncertain is the details of administration, who this work would fund, etc. I think 2i2c can probably take on a subset of this work (maybe all of it, I am not positive though) but we’d need to know relatively quickly. Are others interested in doing pieces of this work as well?

(I should also note, I don’t think that this particular round of funding is mission critical for the project, so it is not the end of the world if we decide to delay for a little bit and apply for the next round)

**Comment by cooperrc** [comment]
I would love to take on a position either on the Jupyter Lab or Jupyter Book side. Doing some development for either interface/extensions and/or MyST markdown/Sphinx and some use cases (I do think we can extend use cases to more than just publishing, be it training material, blog posts, etc.). 

I'm happy to help, but I don't want to step on toes. Let me know what you need.

**Comment by choldgraf** [comment]
@cooperrc - I have a feeling that we are rushing things a little bit with this proposal. What do you say we skip this round, and brainstorm ideas for a subsequent round (or a different funding stream). If you have any thoughts or ideas I'd love to chat!

**Comment by cooperrc** [comment]
> @cooperrc - I have a feeling that we are rushing things a little bit with this proposal. What do you say we skip this round, and brainstorm ideas for a subsequent round (or a different funding stream). If you have any thoughts or ideas I'd love to chat!

:+1: Sounds good. I know you're juggling a few proposals right now.

**Comment by choldgraf** [comment]
I'm gonna close this one, but I think we should keep an eye out for funding opportunities or another EOSS call. @cooperrc if you're interested in pitching in - what kinda work are you hoping to collaborate on? And do you imagine finding funding for your own time, or students/post-docs/etc time? (you're a professor right?)

**Comment by cooperrc** [comment]
> I'm gonna close this one, but I think we should keep an eye out for funding opportunities or another EOSS call. @cooperrc if you're interested in pitching in - what kinda work are you hoping to collaborate on? And do you imagine finding funding for your own time, or students/post-docs/etc time? (you're a professor right?)

Yes, I'm a professor (covered 9-out-of-12 months). Ideally, I could cover some Summer salary. Student funding would be ideal, but it depends upon funding timeframe (<6 mos = undergrad, 0.5-2 yr = masters, >2 yr = Ph.D.).
