### ISSUE TITLE
Update a few logos across the projects?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#345]
I noticed that some of our logos hadn't been updated in a while, and was wondering if we could update the Jupyter Book logo a bit, and apply a similar design style to the other projects.

I'm curious what folks think - perhaps we could adopt this set of logos for some consistent style? (I think that eventually, we should hire an actual designer to create the logos, but this is more like an intermediate improvement)

Updated logos:

- [x] Jupyter Book
- [x] MyST Parser
- [x] Sphinx Book Theme
- [x] MyST NB https://github.com/executablebooks/MyST-NB/pull/336

**Comment by choldgraf** [comment]
Here's another mock-up with **Garamond** instead of Roboto Slab. :-)

![image](https://user-images.githubusercontent.com/1839645/117353016-7f431f00-ae64-11eb-9583-c0f8e5cf8d72.png)

**Comment by chrisjsewell** [comment]
yep looks to be a good iterative improvement to me 👍

**Comment by chrisjsewell** [comment]
@choldgraf can you add a page to the project documentation regarding the logo design guidelines, as currently documented in https://docs.google.com/presentation/d/1l7fYEkjd0Dq1MdGxEqsFFSu-QYRrMFXs_N8euZzP2vQ/edit#slide=id.gde7d5d9cee_0_0, cheers

**Comment by chrisjsewell** [comment]
I've started adding them to https://www.figma.com/file/ZptZUfzGznnT8GhIplnZBU/icon?node-id=0%3A1

**Comment by choldgraf** [comment]
Ya good call - I saw the figma invite too so will give that a look and document as well when I have a moment. This week is a bit crazy with travel prep so no promises but I will try and make the time

**Comment by chrisjsewell** [comment]
no worries, note also that in https://www.figma.com/file/ZptZUfzGznnT8GhIplnZBU/icon?node-id=0%3A1, I have also now added a white background (with rounded corners) to the square logos (i.e. favicons),
so that they are still visible in dark theme, e.g.

<img width="203" alt="image" src="https://user-images.githubusercontent.com/2997570/128210124-284dd0d0-8c5c-4a86-b0a7-33a871c504f3.png">

This should be rolled out to the repos above
