### ISSUE TITLE
Decide and document our coding style for javascript / typescript

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#375]
In https://github.com/executablebooks/markdown-it-myst/pull/30 we've now enforced a particular code style on the typescript (and implicitly, Javascript) codebase that we've got. In particular, I think this prettier configuration is what is used there:

https://github.com/executablebooks/markdown-it-myst/commit/c517f5c0a437b5b24038fa85c3605c302804069d#diff-663ade211b3a1552162de21c4031fcd16be99407aae5ceecbb491a2efc43d5d2 

So first of all, we should make sure that this is a 👍 for folks working on the Javascript side (maybe from the @executablebooks/web-team in particular). I don't know Javascript well enough to have strong opinions about code formatting there, though this seems reasonable enough to me.

If we agree that this is a good formatting choice, we should document it in our conventions so that others know what standard we should follow.

**Comment by rowanc1** [comment]
Happy to use prettier and enforce code-style in a similar way to how things are working on the python repos, and enjoyed seeing the `code-cov` addition there.

Wondering if we can just take the style from jupyterlab here?
https://github.com/jupyterlab/jupyterlab/blob/master/.prettierrc

Specifically keeping semi-colons (realize that it may be jarring coming from python...). This is relatively standard across all of the repos/demos that I am seeing from major projects (react, redux, svelte, vue, material-ui, jupyterlab), is part of the js language (reducing ambiguity in return statements, function closures, etc.), and I believe in the recommended spec for prettier as well. It would be nice, in my opinion, to stay in family with other javascript projects as we have the ability to bring on maintainers (such as myself) from those worlds.

I was using 100 character print-length in the repos that I am involved in, but am not too fussy about that one.

Looking forward to thoughts from @chrisjsewell.

**Comment by chrisjsewell** [comment]
Yeh so just in general for any coding language, you can break it down to the critical components:

- Have (CI tested) automatic formatting (python=black, javascript=prettier)
- Have (CI tested) linting (python=flake8, javascript=eslint)
- Have CI unit testing (python=pytest, javascript=jest, I also like ava but jest seems to be the standard in a lot of projects)
- Have unit testing code coverage (via code-cov)
- Have automated, continuous deployment (e.g. python to pypi, javascript to npm)

Also the use of pre-commit is general, in python I have it set up to do all the formatting/linting. This could also be done for javascript (although I found eslint to be quite slow when doing this)

On top of that, where possible have type annotations and checking (python=mypy, javascript=typescript).

In terms of formatting specifics: black is obviously nice because its very opinionated, and there is no configuration needed.
For line length, it uses 88, for reasons it explains in detail. Therefore, I think we should also use this for javascript.
For semi-colons, nope completely against them; if a formatter can automatically remove them in most cases, then they are clearly superfluous to the syntax of the language, plus the `{}`s perform the function of removing ambiguity perfectly well. That's nothing to do with coming from Python.
I can point you to plenty of pieces supporting this stance (e.g. https://medium.com/@eugenkiss/dont-use-semicolons-in-typescript-474ccfe4bdb3), but mainly it should not matter in the slightest to developers because that's the whole point of automated formatting, you don't have to think about it (if you add semi-colons while writing they will just be removed when you hit format). IMHO you have to be a pretty bad programmer if the presence or lack of semi-colons puts you off contributing to a project 😜 

For javascript there was also the question of npm vs yarn, but basically these days they are exactly equivalent, so not a big deal either way I don't think.

**Comment by chrisjsewell** [comment]
another minor point; I added this to the markdown-it-myst eslint (taken from jupyterlab):

```
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "interface",
        "format": [
          "PascalCase"
        ],
        "custom": {
          "regex": "^I[A-Z]",
          "match": true
        }
      }
    ],
```

i.e. all interfaces should start with `I`

**Comment by chrisjsewell** [comment]
also also, I guess another component of javascript is the choice of bundler. webpack is usually the de facto standard, although I didn't want to have a little look into the others (gulp, rollup, parcel, etc)

I guess equivalent in python is the choice of packager. again setuptools is the defacto standard, but there is also e.g flit and poetry

**Comment by chrisjsewell** [comment]
also also also (lol) it kind of goes without saying these days that Github Actions is the standard for running CI (over travis, circle ci, etc). Even though @choldgraf hates microsoft and their FOSS monopoly 😆

**Comment by chrisjsewell** [comment]
also also also also on final generic thing that I will keep moaning at pepole about: **comment your code!** (as in internal code comments and docstrings). Just because it's clear to you what the code does, it probably won't be to anyone else, you should be trying to explain each step of logic in your code; what it purpose is, anything other should be aware of if they are thinking of refactoring it, etc

**Comment by choldgraf** [comment]
Hey all - thanks for the discussion. I'm gonna limit my comments to **code style of Typescript**, I think @chrisjsewell makes a bunch of good points about CI/CD infrastructure standards etc, but to help focus conversation I'll narrow my scope. IMO we can and should discuss standardizing infrastructure but in another issue.

It seems like there are two main discussion points:

## Line length

@chrisjsewell feels strongly about 88, @rowanc1 doesn't seem to feel strongly. Black [has nice justification for this](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length) and we already use this convention with the Python repositories, so I'm +1 on 88 as well since it'd standardize across our repos and match Black conventions.

## Semicolons

@chrisjsewell feels strongly that they shouldn't exist, @rowanc1 believes (unclear how strongly) that using semicolons would be more friendly to people coming from the javascript world. So I think this is the main one to resolve.

My opinion: it doesn't seem like there's a functional difference between them (although maybe some edge-cases where adding a `;` will avoid esoteric errors). I think we should optimize for whatever will be easiest for javascript developers to understand. I agree with @chrisjsewell that because we're auto-formatting, people can write the code however they'd like and the auto-formatter will make the corrections for them, so mostly this is a question of what will make the code easier to **read** than to write.

I don't have strong opinions on that one, maybe @rowanc1 or others on the @executablebooks/web-team has thoughts?

**Comment by rowanc1** [comment]
Re: semicolons. I didn't realize I was walking into a strongly held opinion here, just suggesting we follow what other major projects do to improve familiarity. I am happy with whatever choice is made.

**Comment by chrisjsewell** [comment]
FYI I have now created https://github.com/executablebooks/markdown-it-plugin-template, which includes a lot of the points I have mentioned above (and discusses some rationale in the README)

**Comment by rowanc1** [comment]
I revisited this issue through the linked community strategy document, and I think that this can now be closed. We have standardized the template across all typescript repos in executable books with feedback from myself, @chrisjsewell, and @stevejpurves.

e.g. see https://github.com/executablebooks/markdown-it-plugin-template/pull/11, we will continue to evolve some of these over time.
