### ISSUE TITLE
ruamel or pyyaml?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#38]
I seem to remember in a conversation with @chrisjsewell that he really liked ruamel.yaml. However I noticed that pyyaml is used quite a lot in our various repositories. I've used both before, and think ruamel is *much* more fully-featured, though a bit more complex to use. I'm curious if folks have thoughts on this. It would probably be best if we just used a single YAML package...

**Comment by chrisjsewell** [comment]
Yeh I'd say stick with `pyyaml` since its already in the dependency chain (FYI if you want to see all the indirect dependencies of your package, you can use [pip-compile](https://github.com/jazzband/pip-tools)).
Before a large security bug in pyyaml got patched last year I would have said definitely ruamel.yaml. But I'd only say use it now if you actually need the added features (e.g. comment round-tripping).

Plus ruamel.yaml is on sourceforge 👎 👎

**Comment by choldgraf** [comment]
sourceforge nooooooooooo


Sounds good, I am +1 on `pyyaml` as long as there aren't any dealbreakers. I don't think that we need to do anything like complex round-tripping of YAML, and as long as it can parse YAML comments I'm fine using it. Will switch over to pyyaml wherever I use ruamel in my repos then.

**Comment by chrisjsewell** [comment]
pyaml it is
